name: roole_element
version: 0.5.0
author: Salomon BRYS <salomon.brys@gmail.com>
description: Integrates roole css processor inside polymer.dart
homepage: https://github.com/SalomonBrys/dart-roole-element
documentation: https://github.com/SalomonBrys/dart-roole-element
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  js: '>=0.2.0'
  styleproc_element: '>=0.2.0 <0.3.0'
